version: '3'

networks:
  app:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: swinwebserver
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - app

  mysql:
    image: mysql:5.7.22
    container_name: swindatabase
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swinapp
    volumes:
      - ./:/var/www
    ports:
      - 8008:80
    networks:
      - app
